services:
  - type: web
    name: ai-resume-scanner
    env: python
    plan: free
    region: singapore  # Change to your preferred region: oregon, frankfurt, etc.

    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

    autoDeploy: true
